CREATE TABLE bulk."paymentHistory"  (
    "paymentHistoryId" BIGSERIAL,
    "actorId" VARCHAR(25) NOT NULL,
    "paymentId" BIGINT,
    "batchId" INTEGER,
    "sequenceNumber" INTEGER,
    "identifier" VARCHAR(25),
    "account" VARCHAR(255),
    "spspServer" VARCHAR(255),
    "firstName" VARCHAR(255),
    "lastName" VARCHAR(255),
    "dob" timestamp without time zone,
    "nationalId" VARCHAR(255),
    "amount" numeric(19,2),
    "paymentStatusId" SMALLINT,
    "info" TEXT,
    "createdAt" timestamp without time zone NOT NULL,
    CONSTRAINT "pkBulkPaymentHistory" PRIMARY KEY ("paymentHistoryId"),
    CONSTRAINT "fkBulkPaymentHistory_bulkPayment" FOREIGN KEY ("paymentId") REFERENCES bulk."payment"("paymentId"),
    CONSTRAINT "fkBulkPaymentHistory_bulkBatch" FOREIGN KEY ("batchId") REFERENCES bulk."batch"("batchId"),
    CONSTRAINT "fkBulkPayment_bulkPaymentStatus" FOREIGN KEY ("paymentStatusId") REFERENCES bulk."paymentStatus"("paymentStatusId")
)
